title: "Dev App Store Experience"
steps:
  - name: "HOMEPAGE"
    screen: "homepage.html"
  - name: "XERO SIGNUP"
    screen: "xero-signup.html"
  - name: "XERO LOGIN"
    screen: "xero-login.html"
  - name: "APPS TAB (EMPTY STATE)"
    screen: "apps-tab-empty.html"
  - name: "ADD A NEW XERO APP STORE APP"
    screen: "add-app.html"
  - name: "TELL US ABOUT YOUR APP"
    screen: "tell-us-about-app.html"
  - name: "INTEGRATION DETAILS"
    screen: "integration-details.html"
  - name: "INTEGRATION DETAILS, PAGE TWO"
    screen: "integration-details-2.html"
  - name: "STILL TO DO FORM"
    screen: "still-to-do.html"
  - name: "APP DETAILS CONFIRM"
    screen: "app-details-confirm.html"
  - name: "APP READINESS"
    screen: "app-readiness.html"
  - name: "TERMS AND CONDITIONS"
    screen: "terms-conditions.html"
